---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: brighter-db-credentials
  namespace: brighter
spec:
  encryptedData:
    password: AgBrut0OlhHRx5+o8pMs5ueopVAV3Xn+g/3wH3ZiJqlDFpbZnlJ8nJZ3OjkB6HFoq/+WIh72DRRQ89voD3HpqK2+/Jhx3Pgu1owtAIRfBZRS49gTxdJIyWhK/t21T4XsdaoOyS15B96I1gags3lOA1GclCHYyhwEIMN9p8blLchpKxHJvlFZmMX+bnGi8ACJu2x2z45y+h8Q5n1kRTskwlL0ILlzY/THJ5Jiw7YUkqzQYimItPFI8CzntqZjy/cXAh0ntmERmCry534s1V6JY5qMroDr+CB2+lHz5wPGznGtPMRwnUmYgf7TrGPT/asLHz5nXnlpxgYrHeDYYAkodLC4VlgMYXLKa9ga2p2vxMHieVe690DmUG3RmYR1Jq8Chz0ZDhoJA+PhRiKyuO2xbJBbKOmPzDqdsY5Y93LSSeIdUSOjB1Cgq1J61InZdWdPHxjoEUd+cC5ubjXfsyqBIQLoGCCZc8SYyUHBDNxcs2rWjAldeQTIh5X06dZAKnk/QqhQ5CRv1L5A57B2weVWxbxEMz9xuqtc9cZj600yTbWsKuybljv430O67ZYcBEA8j6l+s7cTDJ6caUujd38ZiJAhhrxN0ZOfQsSixdxaah2ftT+njfBYWvG7Ej0MuGofn9TOIv0GIsJbOAGIIwFfJltOLhuoHUQ00gYwSDAn/g4ePZxTTZf5vHOadG8zWYDlY2dpJQ3iK00EaQ==
    username: AgBYCZOpffQgN3etKvO4J/YdgDN6O8PLTP5YxJgTp/ZDiNMTZBoL4jhvSoR5rkTYK79Zv9kIQaENYuhLkJpw9g3Z9qOa+zKqyOoh026rgtptdMdokbDswNVExd3wFdlu/eFSll/y/DVw37L0soPeKm8OXAQNdiWXDVGtfDw1LnR44YfssN3DucK+cK0upXCVd7wNbMNYhHAurTR32ZjgvpOJnKxaj3VOpbr7fbWOvFvoThFhWNx2tsV265juE2lThJtoJ2MiYq4lExRDpsQ5uBQjjq1SaL8akfp/veLN9dgGSz98ebQ80mhj35pZc1DrAwDT68xXUtjHhlgaJFEnxu6Kgn2lK5m1vfnThpS6psjQFqHrnLAdyIuQMNY7vFhHEF3u7XQtG29a2IXHBTwJkqflz94/iDGy5G/LZ4hxfowGQIhpYN66EY6DDrFdmaODATHyDyzKATSF7ItSOHwuZ38IPrFC1Bwo6eev0Jx8lh9pMcyMzSTYHEcngB4S4ghYHLjplM5IIQaG6eJWCrp/PwQDqi0bxHS1X/QDbQuIXFLgddQ2ZKpEgEL4/zQWozlQqhZiFOzGBizfkqCY6D2ol0YdJLlPvck+ls50kV5k1raMfK71jRbp0VZbjMLZEkh3UWJ7JG1cksJrw8MN+JTdITd/7CXk2yxo+Jl/jqgUsVplRXa0HG4oNzlnDGGfa5cJEL77i+flZ+ubKA==
  template:
    metadata:
      name: brighter-db-credentials
      namespace: brighter
