---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: brighter-db-credentials
  namespace: default
spec:
  encryptedData:
    password: AgCpLvzezcwdWxfLJRos1VVWkzR8KTiUkn4x2Ph9G2K+y6ERTiso7j4kKyYHROEP8WJTk9Rjrw6PQ4Jv879AvSZd8JpxhfsGNk+81rSHLUmrIQSTti5UTqRdz/zlP16vpWg8VWVoGRKAWUhs9Fn64ovZOE0wMSWFaGB3nR6vhvLQOzwuqJna25KGEBEcFhOkUmm4MxAuaPggeijHLfjQbF8u3WYGdFLTEFOSHXdcyDQBOtb1QtPJOLl5scl/Hg1211A7dcWXO15HFHeQfsYC14rxSAiS1sakzlIx09V0Kic8I8RkQky5malK+dHkeVSoY74HAfeDXrEMPL/qsaOQWGJRr5rtH16bazXQpJ8mV7TtPviHtgJe6SKc11kh0qQYm+biE4kGow/Pict8J3G2usJpEX15kre5VvU62lKNGkbudqXbOodorX1DNdZ+owcg6PNoZA+rcvdRx8ZGOS8K2tpU8hRy4971m0Zo6KtkRy0SgVjB1gkuuvXWyKWp2D9X7WWalFVzQJIsonSQci6rWm0vOHJAlUarU6OSaWWk/Yc9s0sXLmEzSS106mzZqYSnGNhptuPG048VLUKaHviukJ8La591LHPr+BxQmRSsZ4VRrnaHDHJMorFZ5BsdVFWVU8bLzLPExExTA2R40iAg5kl4ZhYGyhgRi/L2eFxwlNRWC9HJ4PZwUNqbcvlx97u1AeYwVbx2gtU2Hg==
    username: AgA/2umog6BNU42QV/sZYVIbEWa5Mdp2GvIHFTtc2Gf5tQ3Krpde0xHzJJimmdrv4m2XlEnOKnXFCM2F7+kIRnawgZCcq+721eTA0qY6ztziY92wM7bxRTogq8tddBQdLjrW0iA4YUB42Us0D5sVUcy9d+g0p+xE54dXCyKBdBGEzRybSSS4pgAGRN8c2432xXmCMpxdggQwvoVboNbPFIosFcKGxXR1CEBs5bv8slPB/BXvxZOIl1fT+U89kN+q7xNvvJr6CIBR+EInS/N5vSTTZbP9y4U+LGsjnR+b4/zSl1PwxgET1Fq9kWKF74RQjpTAiMMCPjGnok28tGOxxY5NJG+NU4afad/fUIurcGuwKimJP12btv50OOjZod1m6ULDg41Az7AF9kkZju4WR0AhBH7KbqvS4V/KA19lac5KQI9j3GEMma0D3wnGvH8ZLeS9IxpVdt5ozNLF10KBwCJNiLCaHj6iMiNC5gbk6L45lDJZo3pyy2E+8Yo4OA1UncPk+/9rVyIY1p9xL5qHSE7MlyiqdhUyE5sbv3hdJHnw1UPn+sm2xr+iZ6sNDiQ+u9ZsoVxSdngb+60jQ1ypV1c8R+S7XDqtCdQoPALrUhrZHcREeOgIYHUTQakOfuNatW6wYZd1qOcbHBhPsUCYkWqHksbqS714lpcdSvXyWEuYf02L9NHFZn0LIpATcxLB9eHT/hRKxquroQ==
  template:
    metadata:
      name: brighter-db-credentials
      namespace: default
