---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: brighter
spec:
  encryptedData:
    admin-password: AgArJOPAhDCUdpzJMRitOiJvdn+sYrTQ1J9GqgsPNoLA1d7ZTVHFmb4dyfwWDfdLX1EM2wNKJneGUhFU6BoHjvDhc82rbDYp7SWI8fveTZpZa5UmdoUHaHShViZl0KS6ZnF42Wae0IX71KS9pgjZHUNNoTrPxM44rsudEhnN7BG4lQVn8XflbMvfYfwtq6ezuNJ14mfVpptQCGZntx1xJHkzjinZRxLUiDfaoLbD2Y/zvLQaNV2CEjIbIwGecmcvC9edZjmQ5NLfYBV4XK0/6yfEX+c7ZppfBSauqBCPlYJF+OYV4ltXGUokJqxwa6B3NOKgsnf7OPAM6vxRFhCwaqS266eTmoTYBQTMnsFZ7qYT78AuiXC+4A7sDGPQOIL2UcISxREeBvBUwPWD5wzN3JkK42jH+Br7edNmSXqDujQk9uoNeqVEsw8s1PBvJ5mhMMOMUW4QFjlfVMC+2RR3uTtG8CQZA25vE3qtB05V7UbKZph15prQxucoLqvLeleFoRQuf2HIfdKi4wNlg7l2A4GeB8EZvmuH0/tOp8fmMYpMJXks+1SgifXhddUiquL8YDvFrPbreD/Yd5aMKSg5TofwWE+nUj1DzJOiSiYsGpHgrSyDsHxiGJhkbAFqLrERs+zmofxAKibmdeRId7BrBAB0UuiCkzU2rNCKSynvtrg67dL3LCsxciG4d6wISWlUyUkddIP1jQ==
    admin-user: AgBEz/8FmmebfdvnJhzZoL4oFS1vuju9EGkmj3Cc6GcrmV/vdYCyui2NeeJyBfGywxTLW2ASc+xHMvpHQQuF6kYcOTl+0mkp6SCSPF7Usyd8vXoK4V8eWhwEqf/cj0TeRxNbsrjfmb9AKYLPXB6kqV7MuGxYpGOiq3+hG6KkpIBNkWb0stW6CH+QLdBV7H8XEBSD+uD0zvQ/+DakD/E1zh3MJMV/LAL687aR8mLfaB1oTCyg43CZkdnykXPGiy9RAkxgS3WipRIwo0x2oIStZ8cBD0nGquYoLOS0E+4X5kaJd7h80XoVtOZux5szOHgaN251MjL1QXxXtf/rnhLPKunMbMd3KSWTj6E37D0jCZvfBV2nXgjUVdW4/XRy+gIhpuWiR+bgURXVWH7PdoQJvVnIyGDPBZrM5/6PtUHZ7tE6AcEQyzisTznwPG++iG2PQloMPIkkM5Ux/nnOuWDNl9y2TmFCEuSEAN3sMj0DRgcKs2BuzmQvOLdXcknNG8euWJLw0noR1H0jC6hGvyFMgDJN73mHP+nOjv0pUrVl+BNHIsmk3IeHh5X2bD31Wpdmf5no7zeaqyUyozpPLZyW/WGswtU9iGHiU4/ndx7DpM3sJNeKNzS3+jVOIAyW58QtsIM9Q603ggHWH1N8GQPWvu4QCYi1slG/ZnN5XDdX+sG8WFO/UBk0badOaXbkjfYjcUxCiZGLAw==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: brighter
