---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-alerting-secrets
  namespace: brighter
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgBHM0F/Qr1RQzffFAVtJvEwcWYaZjuN0BlyJIHoZaUoylF5jAAVNDKsYE0n7R1XSOBD+IZoQqzQQQd8nWMgGKzFDAAlKI4CmJrTunM26GWTwwRtphRD9jl5A36FdsAbnEB6S8W3/9oTy3mmB5A1BBMQmPJyEGkcp3Z64p5EWlSM2vq6RJkZBj5FQV4yxF02ccP4QAwEdI277brZww4p9L5PQU3koap3LCqEEZeV+akqDrC3GOQY9mOmSysOLOybpHpkxJ6bBNG0V036aLXBjk/K+334PFYhwdZ9FaymkkX9lp3SFH5Vi2ic0hQKFgsPBHls7UxyOCT8D8BeLmtX09LVI9wEyTFlTt0+1bcyN4NyfpisVmSuwgiVn7171GbfEntKrTqF5PuhSCnyooxDDm0LeZBKNzh5LIhY28G2HC3R4ZPAPz1CwLkXlmsYACF4B859BEnYXkVbLjNkxn6dPBn3fhEaD4E4BY6r0EitHjMRWPOgxjAJwK9DNsuYTcSo1zJEacNZmE8Y+8bg7aPLgPzWh+htRrq/Gc7obHir6gPKuAYpiq1M8WWPEYFbEfOAjKS0i5IaxFZZx4o6raV7/C0JygmFv9p/Qv0j4rRa64qvxf308oKxGT4mBoAJ/IlRxAq7Iu2re5+MyEyUqGrLfgKwOHWtRhez1jnPS6GZtXpozHbcptIoSLUDaOkdBbSLuchoOTioYn9GPaq3/b5eM398fixQDgs9ciL2dgQRkOfWQDZnCUvzWZHvC7pxiKau
  template:
    metadata:
      name: grafana-alerting-secrets
      namespace: brighter
