---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notifications-ms-secrets
  namespace: brighter
spec:
  encryptedData:
    RESEND_API_KEY: AgAuBQK/siPdcBNgIOvjiWVjR3VMUzLdCwInDequxBa7PrW8qJk11PKv6AWSn9TDPR0MiZjwfVGSNp3ecefEKjL8RfNNbWERoh2sjKM6+khtHiTbqjahZgW4cxdygIpiYs4xzTqErArSHthBqGwCpCTi1wu9H/vEmwa6b7OrV8kxhvbU38hg1HNJmEpdT7XdldoY/77GBOnJ8PhhXGS1fBNXZQHpQIX4j2T/pOTnD8QHfES8f1ug4GTPcUTQM1W55m/YICYGSZaW7rgOynqcPRGRGNGV4WsBF6zWZdsebJ48bAAMKKE4opCdAnapD/4t8dSSImfqmJ2x8LmVaS4vPmJX0322Jk1FCYGmq971sLSdQMxhOdjEIffTEuao7xZh1okuOqkSWJxuaFTOgb6KMket4FXmuBGivCEMHetfGPdGAeRm6w3GSBJKw+n7NI6HKTK3A7uLC4RwPTqMEWtvCaihLMMBeDJGJCm15hRylcd89zK0Avv6L7orhJlbQgYqRZ9GfA50h976mcbsA8njTiadUpdbaBZ8UxCFcrJ3edtckiStXM8UQUpzwsbgZk34UjIwTtvQlI3Si/XVnNcfMDYhTePcJ6m9ZYEUd0f6KvGPvukHjDxgL8WHbu9PDYBntYbL3HaQ0eYjgCz6r9TxW0qRZDv/pYKjBggQSsi9quyLtfcFwHQ/vqJVsTIxTJnCHFSbzOphJWOtiONgn/xpI9Yz/dRodi/6WnHfTYZ89jr71hS4QLA=
  template:
    metadata:
      name: notifications-ms-secrets
      namespace: brighter
