---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notifications-ms-secrets
  namespace: default
spec:
  encryptedData:
    RESEND_API_KEY: AgCOQxZJfnPt1wlWwDQeaX8ZTqNest8wYH7DPw6uPgLZRaAHST/V6ocgs1KRuvaTTFPiKdImzM8egNjacMIeHHBwfsQwrb15zyOpZJs455l2Z8ZhTBm2TJhkYYvRqzXCj+ap6CXdp7P/FDbwpBvy1ddyv30jk0i18Udk7HaxRz+HJSVnlPexCPZeIK7rXaSnPF/gHdjyMn7YPAMxlMgLwKZcRGRBkw16v30Gefuy332oD/mk9SqyD10fyhDvcxwH6IsBaxf6EypDoYgfDsWqQHTqXDJ+ClfkMSbYvh3G0ldh5TnRxXsBDmeUkfsP8/fEFUtC3l8Fiq0haI0e32WrJKsBDtI5npKKOv9/goKOubbS+JY7PWKcKSiiOiZJ55M3GoxeIDN5gaxHc2/PpYquOrjJ8pE3SB2Ky4hhUr9YPYlR0z8SaLjeqgFR8qqDg2/XVDNMkRiLtsORxM1/fXZrSQNkZrsZC8yQTzlLyb2PCwDfZrJnnRPdWEIAhOtTW3ZetXhlEsIY0CeCmbF9JHCEpijdDxdahlAs7pksBlBeSBAITAnJbDMca2KQoIxEB+WloPjz/sdOM9V1UPqMbR2QMp5udMiv6o37+MJqAZy0XDgVrw8TPdoTxPL9+2QWnCVsSt0hmjKfOtY3ODFwCksMW1rt7sKvwXPlZ/zCQu3LxoJyXrdxw95wNH4mbgq98UoL3aWm2mNyEyrpy11Gg80SXShLS1CiAZ+zb3hcVFt1ZycL8OLiNi8=
  template:
    metadata:
      name: notifications-ms-secrets
      namespace: default
