---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notifications-ms-secrets
  namespace: default
spec:
  encryptedData:
    RESEND_API_KEY: AgBre53XN9FulJkYwuEuJRI27OKaXb6Vnonk/qv02MSqDe3iJWlESjkb/hDNGOy6afbbHXRM1MIgZNArZ0G1CUSAndgzgsiVKZGtNPSpkbxUd0wpUhDxvnxMYfRbyJwPI4Ecs4AbKpNKA2C397JHLC1Itt3jCYxMlGu0CUFRASPnOkLffTLJ0n2FbRwURs751ezF3Wh1cPWzf/pKa0XGfmu+f2LIVNEib6lNJL5I6aP73J5cIzbQ2gJMScQba7vu7b4mZ/F7jqqxcUdzvhsb4hx+3EsLD9CKiiYj7QPJNZ/eZMsygXtZ7EdESMlaQjxKL5KNBVEQNEuPz8G2Q1+C/B4bE7Lz2tIaZIKj6qK9htH7QvoL5kbato7aOgkw5+3X6t/z8asLaRma2otmtW50rGpMjdH0nxhJpZNWHCe6B65GQOf0RCo9PYRXBuSyfDksQOwtB7FeJG6S981H25q6TLzVvALU1J3Vk1cUQHgKUTgyF0itQNzR6AbPNnADp9JgW9tZWdeFbV4ygtd0MvV9B6p/RrF0rk7CWlEib8e3YMH0izeuHCNLbP3FfOWN3iZ0Z8Fgj1AdoX8dh1VCagzFTsE6O/pKMVYjMfhoCCkzc6SUZI0yUxsbJhSD9sWD4i36aIVFqhvgk1BNoH54UHmduUTCdMHBys5XSeL4l9Vprv3rmL0ce8QoSOm5ha4Ra7MU7Il1sg0OVCN7wNOruuztx2+9ujMqE5gRxaeD2/T7Bajp5mWe++c=
  template:
    metadata:
      name: notifications-ms-secrets
      namespace: default
