{{- if .Values.observability.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: brighter-grafana-alerting
  namespace: {{ .Release.Namespace }}
data:
  contact-points.yaml: |
{{ .Files.Get "alerting/contact-points.yaml" | indent 4 }}
  notification-policies.yaml: |
{{ .Files.Get "alerting/notification-policies.yaml" | indent 4 }}
  rules.yaml: |
{{ .Files.Get "alerting/rules.yaml" | indent 4 }}
{{- end }}
