{{- if .Values.observability.enabled }}
{{- range list "users-ms" "properties-ms" "bookings-ms" "payments-ms" "notifications-ms" }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ . }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
{{- end }}
